imports:
  - { resource: services/collectors.yml }
  - { resource: services/chains.yml }
  - { resource: services/dumpers.yml }
  - { resource: services/compressors.yml }
  - { resource: services/savers.yml }
  - { resource: services/processors.yml }
  - { resource: services/commands.yml }
  - { resource: services/helpers.yml }
  - { resource: services/resolvers.yml }
  - { resource: services/events.yml }
  - { resource: services/garbage.yml }