easy_backups:
  strategies:
    -
      identifier: 'main_database'
      description: 'Backuping the main database'
      dump_strategy: database
      dump_settings:
        type: mysql
        options:
          host: localhost
          user: root
          pass: ~
          name: test_wp
      compressor_strategy: tar_xz
      saver_strategy: file_system
    -
      identifier: 'main_database 2'
      description: 'Backuping the main database'
      dump_strategy: database
      dump_settings:
        type: mysql
        options:
          host: localhost
          user: root
          pass: ~
          name: test_wp
      compressor_strategy: tar_xz
      saver_strategy: file_system