#!/usr/bin/env php
<?php
require __DIR__.'/bootstrap.php';
$container = getContainer();

use Symfony\Component\Console\Application;

/*
 * Create the application
 */
$application = new Application();
$commands = $container->findTaggedServiceIds('console.command');
foreach($commands as $commandId => $commandDef){
    $command = $container->get($commandId);
    if ($command instanceof \Symfony\Component\Console\Command\Command){
        $application->add($command);
    }
}

$application->run();
