services:
    chain.compressor:
        class: Compilation\Chain\CompressorChain

    chain.saver:
        class: Compilation\Chain\SaverChain

    chain.dumper.database:
        class: Compilation\Chain\DatabaseDumperChain

    dumper.database.mysql:
        class: Dumper\Database\MySQLDatabaseDumper
        tags:
            - { name: dumper.database, alias: 'mysql' }
    compressor.tar_xz:
        class: Compressor\TarXzCompressor
        tags:
            - { name: compressor, alias: 'tar_xz' }

    saver.file_system:
        class: Saver\FileSystemSaver
        tags:
            - { name: saver, alias: 'file_system' }