services:
    chain.compressor:
        class: Compilation\Chain\CompressorChain

    chain.dumper.database:
        class: Compilation\Chain\DatabaseDumperChain

    dumper.database.mysql:
        class: Dumper\Database\MySQLDatabaseDumper
        tags:
            - { name: dumper.database, alias: 'mysql' }

    compressor.tar_xz:
        class: Compressor\TarXzCompressor
        tags:
            - { name: compressor, alias: 'tar_xz' }