services:
    command.dumper:
        class: Command\DatabaseDumperCommand
        arguments:
          - '@collector.strategies.databases'
          - '@processor.dump.databases'
          - '@events.dispatcher'
        tags:
          - { name: console.command }