services:
    helper.temporary_files:
        class: Helper\TemporaryFilesHelper
        arguments:
          - '%temporary_folder%'
          - '@events.dispatcher'

    helper.shell_executor:
        class: Helper\ShellExecutorHelper

    helper.deepest_common_files_folder:
        class: Helper\DeepestCommonFolderHelper