services:
    processor.dump.databases:
        class: Processor\DatabaseDumperStrategyProcessor
        arguments:
          - '@chain.dumper.database'
          - '@chain.compressor'
          - '@chain.saver'