services:
    saver.file_system:
        class: Saver\FileSystemSaver
        arguments:
            - '@resolver.filename'
            - '%saving_backups_folder%'
        tags:
            - { name: saver, alias: 'file_system' }